### ISSUE TITLE
Batch upgrade modules button doesn't work

### ISSUE THREAD

**Issue by gmclelland** [adrianbj/ProcessModuleToolkit#1]
Hi @adrianbj ,
I noticed when I go to /admin/setup/upgrades/ and click on the "Batch upgrade modules" button, it takes me to /admin/setup/module_toolkit/upgrade/ and gives me an error.

![image](https://cloud.githubusercontent.com/assets/40570/24297121/92fba4a0-106f-11e7-896c-39d803bd6ca4.png)

![upgrades processwire pw3 dev 2017-03-24 08-49-34](https://cloud.githubusercontent.com/assets/40570/24296887/df938bee-106e-11e7-8bbe-b296d5d316be.jpg)

I'll submit a quick pull request to fix it.

This module is very helpful.  Thank you for creating it.  Big time saver!

**Comment by gmclelland** [comment]
Thank you

**Comment by adrianbj** [comment]
Thank you :)
