### ISSUE TITLE
Cleanup doesn't detect all the Processwire Upgrade files

### ISSUE THREAD

**Issue by gmclelland** [adrianbj/ProcessModuleToolkit#3]
I noticed when I run upgrade cleanup, it only detects files that are hidden and prefixed with a period:
ex.  .htaccess-3.0.52.txt or .index=3.0.52.php

I'm still seeing files without the period that need to be cleaned up.
Ex. htaccess-3.0.52.txt and index-3.0.52.php

Can we include those files as well?

**Comment by adrianbj** [comment]
Happy to support this, but I wonder why you are getting those in the first place - I haven't ever noticed those versions before.

I am kinda busy right now - do you feel like putting together a PR to take care of this ?

**Comment by gmclelland** [comment]
I guess it is from these lines https://github.com/ryancramerdesign/ProcessWireUpgrade/blob/309b448048a07a98dc6b56cd7130ed6219b162f3/ProcessWireUpgrade.module#L403-L404

I'll try to create a PR for this.

**Comment by adrianbj** [comment]
Thanks for the PR - it has been accepted, so closing this issue.
